//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFALogisticasInversas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class li_tarimas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public li_tarimas()
        {
            this.li_cajas = new HashSet<li_cajas>();
        }
    
        public int id { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public int statustarimas_Id { get; set; }
        public int logisticainversa_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<li_cajas> li_cajas { get; set; }
        public virtual li_statustarimas li_statustarimas { get; set; }
        public virtual logisticainversa logisticainversa { get; set; }
    }
}
