//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFALogisticasInversas.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3F19C_producccionEntities : DbContext
    {
        internal IEnumerable<object> tarimas;

        public DB_A3F19C_producccionEntities()
            : base("name=DB_A3F19C_producccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<li_cajas> li_cajas { get; set; }
        public virtual DbSet<li_detcajasskus> li_detcajasskus { get; set; }
        public virtual DbSet<li_origen> li_origen { get; set; }
        public virtual DbSet<li_status> li_status { get; set; }
        public virtual DbSet<li_statustarimas> li_statustarimas { get; set; }
        public virtual DbSet<li_tarimas> li_tarimas { get; set; }
        public virtual DbSet<logisticainversa> logisticainversa { get; set; }
        public virtual DbSet<skus> skus { get; set; }
        public virtual DbSet<skusbenavides> skusbenavides { get; set; }
        public virtual DbSet<skusinventarios> skusinventarios { get; set; }
        public virtual DbSet<uom> uom { get; set; }
    }
}
